### PR TITLE
H52root

### LINKED ISSUE #15: Add h52root converter
Move the standalone converter into CHECLabPy

### PR DESCRIPTION
**Pull request by RichardWhite109**
closes #15

### CODE REVIEW

**Comment by watsonjj** [comment]
This branch also contains changes to the examples/simple_r0r1_loop.py added in #29. As that PR has been merged into the master, could you merge cta-chec/CHECLabPy:master into this branch to make sure that example is in the state you intended.

**Comment by watsonjj** [comment]
First by updating your master branch:
`git fetch upstream && git checkout master && git merge upstream/master && git push origin master`
Then updating your h52root branch:
`git checkout h52root && git merge master` (i think)

**Comment by RichardWhite109** [comment]
Ok - think I did that...

**Comment by watsonjj** [comment]
Yep that worked

**Comment by RichardWhite109** [comment]
Great - sorry accidently created a branch from my other branch... but at least I know how to fix it if it happens again!

**Pull request merged**
